import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// this is just assigning a font
const geistSans = Geist({
  variable: "--font-geist-sans", //this is the css variable that it gets assigned to
  subsets: ["latin"],
});

//this too
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//global metadata is used in the header of the main html file, which affects browser SEO behavior
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// this is a react functional component that WRAPS all other pages, so that they all share the same layout
//children is a dynamic prop that loads everything within the app
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
